name: CI deploy to firebase
on:
  push:
    branches:
      - master

machine:
  node:
    version: '10.x'

# Need to install firebase-tools so that the deploy works
dependencies:
  pre:
    - npm install -g firebase-tools

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: bundle exec jekyll build --verbose
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
